export default {
    addr: 'Endereço',
    cep: 'CEP',
    owner: 'Dono',
    street: 'Rua',
    number: 'Número',
    city: 'Cidade',
    neighborhood: 'Bairro',
    document: 'CPF',
    name: 'Nome',
    phone: 'Telefone',
    roles: 'Títulos',
    created_at: 'Criado em',
    started_at: 'Iniciado em',
    finished_at: 'Finalizado em',
    updated_at: 'Atualizado em',
    description: 'Descrição',
    farm: 'Fazenda',
    person: 'Pessoa',
    serv: 'Serviço',
    List: 'pagina de listagem',
    User: 'tela de usuário',
    Serv: 'tela de usuário',
    Farm: 'tela de fazendas',
    Detail: 'tela de detalhes',
    SelUser: 'seleção de usuário',
    SelFarm: 'seleção de fazenda',
    price: 'Preço',
    employee: 'Funcionário',
};
